export { createElement, cloneElement, isValidElement, createRef, Fragment } from './element';
export { useState, useReducer, useEffect, useLayoutEffect, useInsertionEffect, useRef, useMemo, useCallback, useContext, useImperativeHandle, useDebugValue, useId, useTransition, useDeferredValue, useSyncExternalStore, use, useActionState, useFormStatus, useOptimistic, startTransition, } from './hooks';
export { createContext } from './context';
export { Component, PureComponent } from './class';
export { memo, forwardRef, lazy } from './memo';
export { Suspense, StrictMode, Profiler } from './suspense';
export { Children } from './children';
export { ReactSharedInternals } from './shared-internals';
export declare const cache: <T extends Function>(fn: T) => T;
export declare const act: (fn: () => any) => Promise<void>;
export declare function taintUniqueValue(_msg: string, _lifetime: any, _value: any): void;
export declare function taintObjectReference(_msg: string, _object: any): void;
export declare const version = "19.2.3";
import { createElement, cloneElement, isValidElement, createRef } from './element';
import { useState, useReducer, useEffect, useLayoutEffect, useInsertionEffect, useRef, useMemo, useCallback, useContext, useImperativeHandle, useDebugValue, useId, useTransition, useDeferredValue, useSyncExternalStore, use, useActionState, useFormStatus, useOptimistic, startTransition } from './hooks';
import { createContext } from './context';
import { Component, PureComponent } from './class';
import { memo, forwardRef, lazy } from './memo';
declare const _default: {
    createElement: typeof createElement;
    cloneElement: typeof cloneElement;
    isValidElement: typeof isValidElement;
    createRef: typeof createRef;
    Fragment: (props: {
        children?: import("@tanstack/dom-core").ReactNode;
    }) => import("@tanstack/dom-core").ReactElement;
    useState: typeof useState;
    useReducer: typeof useReducer;
    useEffect: typeof useEffect;
    useLayoutEffect: typeof useLayoutEffect;
    useInsertionEffect: typeof useInsertionEffect;
    useRef: typeof useRef;
    useMemo: typeof useMemo;
    useCallback: typeof useCallback;
    useContext: typeof useContext;
    useImperativeHandle: typeof useImperativeHandle;
    useDebugValue: typeof useDebugValue;
    useId: typeof useId;
    useTransition: typeof useTransition;
    useDeferredValue: typeof useDeferredValue;
    useSyncExternalStore: typeof useSyncExternalStore;
    use: typeof use;
    useActionState: typeof useActionState;
    useFormStatus: typeof useFormStatus;
    useOptimistic: typeof useOptimistic;
    startTransition: typeof startTransition;
    createContext: typeof createContext;
    Component: typeof Component;
    PureComponent: typeof PureComponent;
    memo: typeof memo;
    forwardRef: typeof forwardRef;
    lazy: typeof lazy;
    Suspense: (props: {
        children?: any;
        fallback?: any;
    }) => any;
    StrictMode: (props: {
        children?: any;
    }) => any;
    Profiler: (props: {
        id: string;
        onRender?: any;
        children?: any;
    }) => any;
    Children: {
        map(children: import("@tanstack/dom-core").ReactNode, fn: (child: import("@tanstack/dom-core").ReactNode, index: number) => any): any[] | null;
        forEach(children: import("@tanstack/dom-core").ReactNode, fn: (child: import("@tanstack/dom-core").ReactNode, index: number) => void): void;
        count(children: import("@tanstack/dom-core").ReactNode): number;
        toArray(children: import("@tanstack/dom-core").ReactNode): any[];
        only(children: import("@tanstack/dom-core").ReactNode): import("@tanstack/dom-core").ReactElement;
    };
    version: string;
};
export default _default;
